/**
 * Map Binance base asset → CoinGecko ID for FDV/market cap lookups.
 * Only tokens commonly listed on Binance Futures USDT perps.
 */
export const SYMBOL_TO_GECKO_ID: Record<string, string> = {
  ETH: "ethereum",
  BNB: "binancecoin",
  SOL: "solana",
  XRP: "ripple",
  DOGE: "dogecoin",
  ADA: "cardano",
  AVAX: "avalanche-2",
  LINK: "chainlink",
  DOT: "polkadot",
  MATIC: "matic-network",
  UNI: "uniswap",
  ATOM: "cosmos",
  LTC: "litecoin",
  BCH: "bitcoin-cash",
  NEAR: "near",
  FIL: "filecoin",
  APT: "aptos",
  ARB: "arbitrum",
  OP: "optimism",
  SUI: "sui",
  SEI: "sei-network",
  INJ: "injective-protocol",
  TIA: "celestia",
  RENDER: "render-token",
  FET: "fetch-ai",
  IMX: "immutable-x",
  STX: "blockstack",
  AAVE: "aave",
  MKR: "maker",
  CRV: "curve-dao-token",
  LDO: "lido-dao",
  RUNE: "thorchain",
  PEPE: "pepe",
  WIF: "dogwifcoin",
  BONK: "bonk",
  FLOKI: "floki",
  JTO: "jito-governance-token",
  JUP: "jupiter-exchange-solana",
  PENDLE: "pendle",
  PYTH: "pyth-network",
  ENA: "ethena",
  HYPE: "hyperliquid",
  ONDO: "ondo-finance",
  WLD: "worldcoin-wld",
  TRX: "tron",
  HBAR: "hedera-hashgraph",
  ETC: "ethereum-classic",
  TAO: "bittensor",
  ORDI: "ordinals",
  ENS: "ethereum-name-service",
};

/** Symbols to exclude from the screener (stablecoins, wrapped BTC, etc.) */
export const EXCLUDED_SYMBOLS = new Set([
  "BTCUSDT",
  "BTCDOMUSDT",
  "USDCUSDT",
  "TUSDUSDT",
  "BUSDUSDT",
  "FDUSDUSDT",
  "EURUSDT",
]);
